pipeline {
    agent any

    environment {
        // Match this to the actual output folder generated by your Angular build
        ANGULAR_BUILD_PATH = 'dist/pace-crmui/browser/*'
        NGINX_ROOT = '/var/www/messenger.quotedesks.com/'
    }

    stages {
        stage('Preparation') {
            steps {
                echo 'Starting Frontend Deployment for messenger.quotedesks.com...'
                sh 'curl -s -X POST -H "Content-Type: application/json" -H "x-deployment-token: DEPLOYMENT_TOKEN_PACE" -d \'{"status": true}\' http://localhost:3001/api/v1/system/maintenance || true'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install --legacy-peer-deps'
            }
        }

        stage('Build Angular UI') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Deploy to Nginx') {
            steps {
                // Ensure the target directory exists
                sh "sudo mkdir -p ${NGINX_ROOT}"
                
                // Copy the contents of the build directly into the root folder
                sh "sudo cp -R ${ANGULAR_BUILD_PATH} ${NGINX_ROOT}"
                
                // Set the correct permissions for Nginx to serve the files
                sh "sudo chown -R www-data:www-data ${NGINX_ROOT}"
                sh "sudo chmod -R 755 ${NGINX_ROOT}"
            }
        }
    }

    post {
        always {
            cleanWs()
            sh 'sleep 3 && curl -s -X POST -H "Content-Type: application/json" -H "x-deployment-token: DEPLOYMENT_TOKEN_PACE" -d \'{"status": false}\' http://localhost:3001/api/v1/system/maintenance || true'
        }
        success {
            echo "Successfully deployed the frontend to ${NGINX_ROOT}!"
        }
    }
}